version: '3.9'
services:
  backend:
    image: server
    build: .
    restart: unless-stopped
    env_file:
      - .env
    command: yarn run dev
    ports:
      - "${SERVER_EXTERNAL_PORT}:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - "${MONGO_EXTERNAL_PORT}:27017"

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "${ME_EXTERNAL_PORT}:8081"
    depends_on:
      - mongo
    env_file:
      - .env

  redis:
    image: redis
    restart: unless-stopped
